{{ config(materialized='table') }}

with SF_STG_CONTACT as
(
SELECT
UUID_STRING() as MEMBER_PROFILE_ID,
	A."Id" as SF_CONTACT_ID,
	"AccountId" as SF_ACCOUNT_ID,
	A."Name" as MEMBER_NM,
	"Email" as EMAIL_ADDRESS,
	"Secondary_Email__c" as SECONDARY_EMAIL_ADDRESS,
	"Gender__c" as GENDER_NM,
	"Birthdate" as BIRTH_DT,
	"Title" as JOB_TITLE_TXT,
	"Address_Type__c" as MAILING_ADDRESS_TYPE_TXT,
	"MailingStreet" as MAILING_STREET_NM,
	"MailingCity" as MAILING_CITY_NM,
	"MailingState" as MAILING_STATE_CD,
	"MailingPostalCode" as MAILING_POSTAL_CD,
	"MailingCountry" as MAILING_COUNTRY_NM,
	"MailingLatitude" as MAILING_LATITUDE,
	"MailingLongitude" as MAILING_LONGITUDE,
	"HomePhone" as HOME_PHONE_NBR,
	"Work_Phone__c" as WORK_PHONE_NBR,
	"Cell_Phone__c" as CELL_PHONE_NBR,
	"MobilePhone" as MOBILE_PHONE_NBR,
	"OtherPhone" as OTHER_PHONE_NBR,
	"Phone" as PHONE_NBR,
	B."Name" as CHAPTER_LOOKUP_NM,
	"Blue_Star_Jobs__c" as BSF_JOBS_IND,
	"Blue_Star_Museums__c" as BSF_MUSEUMS_IND,
	"Blue_Star_Parks__c" as BSF_OUTDOORS_IND,
	"Blue_Star_Perks__c" as BSF_PERKS_IND,
	"Blue_Star_Theatres__c" as BSF_THEATRES_IND,
	"Books_on_Bases__c" as BOOKS_ON_BASES_IND,
	"Career_Resources__c" as CAREER_RESOURCES_IND,
	"Caregiver__c" as CAREGIVER_IND,
	"Caregiver_Resources__c" as CAREGIVER_RESOURCES_IND,
	"Estimated_ETS_Transition_Date__c" as ESTIMATED_ETS_OR_TRANSITION_DT,
	"ETS_Transition_Resources__c" as ETS_OR_TRANSITION_RESOURCES_IND,
	"Events__c" as EVENTS_IND,
	"Higher_Logic_User__c" as HIGHER_LOGIC_USER_IND,
	"HL_Mod_Date__c" as HIGHER_LOGIC_MODIFIED_DTTM,
	"Membership_Category__c" as MEMBERSHIP_CATEGORY_NM,
	"Military_Children_Resources__c" as MILITARY_CHILDREN_RESOURCES_IND,
	"Military_Family_Affiliation__c" as MILITARY_FAMILY_AFFILIATION_TXT,
	"ParkPassport__c" as PARKPASSPORT_IND,
	"PCS_Move_Resources__c" as PCS_MOVE_RESOURCES_IND,
	"Primary_Branch_Affiliation__c" as PRIMARY_BRANCH_AFFILIATION_TXT,
	"Primary_Race__c" as RACE_OR_ETHNICITY_TXT,
	"Race_Ethnicity_Other__c" as RACE_OR_ETHNICITY_OTHER_TXT,
	"Relationship_to_Service_Member2__c" as RELATIONSHIP_TO_SERVICE_MEMBER_TXT,
	"Research_and_Policy__c" as RESEARCH_AND_POLICY_IND,
	"Bi_Multi_Racial_Other__c" as BI_MULTI_RACIAL_TXT,
	"Virtual_Events__c" as VIRTUAL_EVENTS_IND,
	"Affiliated_Military_Status__c" as AFFILIATED_MILITARY_STATUS_TXT,
	"BSF_Member_Opted_In__c" as BSF_MEMBER_OPTED_IN_IND,
	"Careers_Email_Opt_Out__c" as CAREERS_EMAIL_OPT_OUT_IND,
	"cfg_Number_of_Emails_Opened_This_Year__c" as NUMBER_OF_EMAILS_OPENED_LAST_12_MONTHS_CNT,
	"Hard_Bounce__c" as HARD_BOUNCE_IND,
	"Hard_Bounce_Change_Date__c" as HARD_BOUNCE_CHANGE_DT,
	"HasOptedOutOfEmail" as EMAIL_OPT_OUT_IND,
	"IsDonor__c" as DONOR_IND,
	"IsLead__c" as LEAD_IND,
	"LifeCare_Opt_In__c" as LIFECARE_OPT_IN_IND,
	"LifeCareOptInDate__c" as LIFECARE_OPT_IN_DT,
	"Local_Event_Information_Emails_Opt_Out__c" as LOCAL_EVENT_INFO_EMAILS_OPT_OUT_IND,
	"Local_Newsletter_Email_Opt_Out__c" as LOCAL_NEWSLETTER_EMAIL_OPT_OUT_IND,
	"National_Newsletter_Email_Opt_Out__c" as NATIONAL_NEWSLETTER_EMAIL_OPT_OUT_IND,
	"Text_Messaging__c" as TEXT_MESSAGING_TXT,
	"LinkedIn__c" as LINKEDIN_URL_TXT,
	"Twitter_Handle__c" as TWITTER_HANDLE_TXT,
	"Contact_Record_Source__c" as CONTACT_RECORD_SOURCE_TXT,
	"Contact_Record_Source_Update__c" as CONTACT_RECORD_SOURCE_UPDATE_TXT,
	"BSF_Volunteer__c" as BSF_VOLUNTEER_IND,
	"Volunteer_Application_Submitted__c" as VOLUNTEER_APPLICATION_SUBMITTED_IND,
	"BSF_Volunteer_Opportunities__c" as BSF_VOLUNTEER_OPPORTUNITIES_IND,
	"Volunteer_Experience_And_Skills__c" as VOLUNTEER_EXPERIENCE_AND_SKILLS_TXT,
	"Volunteer_Role_Interest__c" as VOLUNTEER_ROLE_INTEREST_TXT,
	A."CreatedById" as SF_CREATED_BY_ID,
	A."CreatedDate" as SF_CREATED_DTTM,
	A."LastModifiedById" as SF_LAST_MODIFIED_BY_ID,
	A."LastModifiedDate" as SF_LAST_MODIFIED_DTTM,
	'STG_MEMBER_PROFILE_SEMANTIC' as CREATED_BY,
	CURRENT_TIMESTAMP() as CREATED_DTTM,
	'STG_MEMBER_PROFILE_SEMANTIC' as UPDATED_BY,
	CURRENT_TIMESTAMP() as UPDATED_DTTM,
    CURRENT_DATE() as	START_DT,
    '9999-12-31'  as  END_DT
	FROM BSF01_DEV.BSF01_SALESFORCE.SF_STG_CONTACT_temp_20221116 A
    
   LEFT JOIN 
	BSF01_DEV.BSF01_SALESFORCE.STAGE_BSF_LOCATIONS B
	ON A."Chapter_Lookup__c" = B."Id"
) 


select * from SF_STG_CONTACT




